services:
  redis:
    init: true
    restart: always
    command: |
      sh -c '
        if [ "$${ENABLE_REDIS_EMPTY_PASSWORD:-false}" = "true" ]; then
          exec valkey-server
        else
          exec valkey-server --requirepass "$${REDIS_PASSWORD:-redispassword}"
        fi
      '
    environment:
      - "ENABLE_REDIS_EMPTY_PASSWORD=${ENABLE_REDIS_EMPTY_PASSWORD:-false}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}"
    healthcheck:
      test: |
        sh -c '
          if [ "$${ENABLE_REDIS_EMPTY_PASSWORD:-false}" = "true" ]; then
            valkey-cli -p $${REDIS_PORT:-6379} ping | grep -q PONG || exit 1
          else
            valkey-cli -a "$${REDIS_PASSWORD:-redispassword}" -p $${REDIS_PORT:-6379} ping | grep -q PONG || exit 1
          fi
        '
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s
      start_interval: 5s
    volumes:
      - cache_data:/data:Z
    networks:
      - vt_tool_network

volumes:
  cache_data:

networks:
  vt_tool_network:
    external: true
    name: ${NETWORK_NAME}
