name: vt_tool
services:

  vt-tool-api:
    extends:
      file: compose_apps.yaml
      service: vt-tool-api
    image: ${REGISTRY_MIRROR_URL:-}ghcr.io/thalesgroup-cert/vt-tool-api:${VT_TOOL_API_VERSION:-latest}
    build:
      context: ../
      dockerfile: Dockerfile
    pull_policy: build
    container_name: vt-tool-api
    depends_on:
      redis:
        condition: service_healthy

  vt-tool-worker:
    extends:
      file: compose_apps.yaml
      service: vt-tool-worker
    image: ${REGISTRY_MIRROR_URL:-}ghcr.io/thalesgroup-cert/vt-tool-api:${VT_TOOL_API_VERSION:-latest}
    build:
      context: ../
      dockerfile: Dockerfile
    pull_policy: build
    container_name: vt-tool-worker
    depends_on:
      redis:
        condition: service_healthy

  vt-tool-ui:
    extends:
      file: compose_apps.yaml
      service: vt-tool-ui
    image: ${REGISTRY_MIRROR_URL:-}ghcr.io/thalesgroup-cert/vt-tool-ui:${VT_TOOL_UI_VERSION:-latest}
    build:
      context: ../vt-tool-ui
      dockerfile: Dockerfile
    pull_policy: build
    container_name: vt-tool-ui
    depends_on:
      vt-tool-api:
        condition: service_healthy

  redis:
    extends:
      file: compose_databases.yaml
      service: redis
    image: ${REGISTRY_MIRROR_URL:-}valkey/valkey:${REDIS_VERSION:-latest}
    container_name: redis
    restart: always
    healthcheck:
      test: "valkey-cli -a ${REDIS_PASSWORD:-redispassword} ping || exit 1"
      interval: 2s
      timeout: 1s
      retries: 10
      start_period: 30s

networks:
  vt_tool_network:
    external: true
    name: ${NETWORK_NAME}

volumes:
  cache_data:
  vt_tool_cache:
